### ISSUE TITLE
🎨 [Refactor] - game 파일 및 소켓 정리

### ISSUE THREAD

**Issue by cweedlee** [maplepong/docker#14]
## 📝 Description
> 전반적으로...

## ✅ To-do
- [ ] Game 상태별로 컴포넌트 빼기
- [ ] 뒤로가기, 나가기 이벤트리스너 추가
- [ ] 스타일 깨진 부분/ 폰트 정리

## 📚 Etc
- 특이사항
