### ISSUE TITLE
🎨 [Refactor] - api files

### ISSUE THREAD

**Issue by cweedlee** [maplepong/docker#15]
## 📝 Description
> 미사용 api 제거, url 전역변수로 가져오는 방법 필요

## ✅ To-do
- [ ] url 전역변수 필요
- [ ] api.js _api.js apiGame 같은 api인스턴스로 통합
- [ ] 일부 api는 자체적으로 리다이렉션하게 정리 → 로그아웃, game result, 등(확인필요)
- [ ] 리다이렉션 함수들 myReact.redirect로 통합

## 📚 Etc
- 특이사항
