### ISSUE TITLE
✨ [Feat] - 프론트 테스트 환경 조성

### ISSUE THREAD

**Issue by cweedlee** [maplepong/docker#16]
## 📝 Description
> 빌드 및 도커 다시 올리기를 하지 않고 테스트를 하고 싶다...

## ✅ To-do
- [x] node 컨테이너 올리기
- [ ] 그외 파일들 수정
- [ ] 구동 에러 확인

## 📚 Etc
- 특이사항
