### ISSUE TITLE
✨ [Feat] - 프론트 - 토너먼트

### ISSUE THREAD

**Issue by cweedlee** [maplepong/docker#17]
## 📝 Description
> 토너먼트..

## ✅ To-do
- [ ] 소켓 컨트롤러 함수 제작
- [ ] api 제작
- [ ] 대기실 페이지 레이아웃 수정
- [ ] 대진표 페이지 레이아웃

## 📚 Etc
- 특이사항
