### ISSUE TITLE
✨ [Feat] - 내 정보에서 대전 기록 불러와서 파싱하기

### ISSUE THREAD

**Issue by siwolee** [maplepong/docker#37]
## 📝 Description
> 어떤 기능에 대해 요청할지

내정보 - myInfo 컴포넌트에서 대전 기록 불러와서 파싱하기

## ✅ To-do
- [ ] 원이한테 연락해서 api list 대전 기록 관련 업데이트
- [ ] api 함수 제작 및 테스트
- [ ] 만약 대전 기록이 여러종류일 경우 타입 바꾸거나 해서 다 파싱
- [ ] api에 없는 항목은 화면에서 제거

## 📚 Etc
- 특이사항
